Repository chrultrabook/docs, pull requests merged in 2023-08, with the labels that each got.

#47 Extend list of required Debian packages for building coreboot
  docs/compiling-coreboot.md
Labels: documentation, good first issue

#49 2023.08 update
  .github/actions/spelling/allow.txt
  docs/allaboutfirmware.md
  docs/altos.md
  docs/bugreport.md
  docs/compiling-coreboot.md
  docs/contributing.md
  docs/csdriver.md
  docs/debugging.md
  docs/distros.md
  docs/firmware.md
  docs/getting-started.md
  docs/installing-linux.md
  docs/installing-macos.md
  docs/installing-windows.md
  docs/post-install.md
  docs/reverting.md
  docs/signedlicense.md
  docs/supported-devices.md
  docs/system-info.md
  docs/terminology.md
  docs/unbricking.md
  docs/ventoy.md
Labels: enhancement

#50 Added note on how to custom pledge (thx @ethanaobrien)
  docs/csdriver.md
Labels: documentation, enhancement

#51 08.14.2023 Update
  .github/actions/spelling/allow.txt
  assets/flipperunbrick/GPIOSetup.png
  assets/flipperunbrick/README
  docs/bugreport.md
  docs/unbrick-flipper.md
Labels: documentation, enhancement

#55 08.2023 rewrite
  .github/actions/spelling/allow.txt
  .github/workflows/spelling.yml
  docs/advanced.md
  docs/allaboutfirmware.md
  docs/altos.md
  docs/bootableusb.md
  docs/compiling-coreboot.md
  docs/debugging.md
  docs/distros.md
  docs/faq.md
  docs/firmware.md
  docs/getting-started.md
  docs/installing-linux.md
  docs/installing-macos.md
  docs/known-issues.md
  docs/post-install.md
  docs/supported-devices.md
  docs/unbrick-flipper.md
  docs/unbricking.md
Labels: documentation, enhancement, help wanted

#64 Fix supported linux chart
  docs/supported-devices.md
Labels: documentation, enhancement
